;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Character.Ability.Attack",DevComment="")
+GameplayTagList=(Tag="Character.Ability.Hit",DevComment="")
+GameplayTagList=(Tag="Character.State.Attacking",DevComment="")
+GameplayTagList=(Tag="Character.State.Hit",DevComment="")
+GameplayTagList=(Tag="Event.Character.HitCheck",DevComment="")
+GameplayTagList=(Tag="Event.Character.Walk",DevComment="")
+GameplayTagList=(Tag="Event.HitEffect.Finish",DevComment="")
+GameplayTagList=(Tag="Event.HitEffect.Left",DevComment="")
+GameplayTagList=(Tag="Event.HitEffect.Right",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Effect.Hit",DevComment="")

